name: K6 Load Test

# Se ejecuta en push al main o manualmente
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Install K6
        run: |
          curl -s https://api.github.com/repos/grafana/k6/releases/latest \
          | grep "browser_download_url.*linux-amd64.tar.gz" \
          | cut -d '"' -f 4 \
          | wget -qi -
          tar -xzf k6-v*-linux-amd64.tar.gz
          sudo mv k6-v*/k6 /usr/local/bin/
          k6 version

      - name: Run K6 load test
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "Running K6 load test..."
          k6 run test/script_k6.js
