name: K6 Load Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install K6 (binary download)
        run: |
          curl -L https://github.com/grafana/k6/releases/latest/download/k6-v0.51.0-linux-amd64.tar.gz -o k6.tar.gz
          tar -xzf k6.tar.gz
          sudo mv k6-v*/k6 /usr/local/bin/
          k6 version

      - name: Run K6 load test
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          echo "Running K6 test..."
          k6 run tests/load_test.js
